### ISSUE TITLE
[BUG] - LC_API *Cannot Move After Respawning In Game*

### ISSUE THREAD

**Issue by N10ns** [ebkr/r2modmanPlus#1167]
The Bug happens in Lethal Company with the mod, LC_API. 

STEPS TO REPRODUCE:
1. you load into the the game
2. you start, 
3. you play the game normally then die normally,
4. after you respawn, you will not be able to move, just jump. You have to leave and rejoin to fix it, but it will repeat.

**Expected behavior**
You should be able to move normally after respawning.

**Additional context**
I did a lot of troubleshooting and found that LC_API was the one doing it.

**Comment by codakairos** [comment]
This is unrelated to r2modman, please report it directly on the LC-API github: https://github.com/steven4547466/LC-API

**Comment by ArchOwlen** [comment]
As I do not see a bug report on LC-API posted by N10ns, I thought I'd hop in and try to help anyway

This issue is most likely not related to LC_API, as I had this issue as well in regards to other mods 

The mod that caused it for me was Masked Fix (which fixes you being unable to turn when getting masked), where (ironically) it instead made you unable to turn at all

If you require further help, I would recommend joining the Lethal Company Modding Discord for further assistance
(and/or adding me on discord, username Owlen, but the modding discord should be able to help more than myself)

Modding Discord link: https://discord.com/invite/lcmod
