### ISSUE TITLE
Latest setup file just deleted the intstall directory

### ISSUE THREAD

**Issue by Qwerty-Space** [ebkr/r2modmanPlus#148]
Running the latest setup file just deleted the install directory `E:\Programs\r2modman`, and any supsequent run would abort.

**Comment by ebkr** [comment]
Hi, sorry to hear you've had issues with updating. It's recommended to leave auto-updates to the manager, rather than manually downloading the setup file each time.

You can follow this guide to fix the setup aborting: https://github.com/ebkr/r2modmanPlus/wiki/Error:-Installation-Aborted

Failing that, there's also a portable version of the manager available here: https://github.com/ebkr/r2modmanPlus/releases/latest

The portable version is the EXE without "Setup" in the name.

Let me know if this has solved your problem, I'll keep the issue open for a few hours in case there's any problems.

**Comment by Qwerty-Space** [comment]
The banner told me there was an update, and clicking it took me to the releases page.

Maybe that functionality should be removed then?

**Comment by ebkr** [comment]
Were you already using the portable version? That banner should only appear in the portable version.

The difference between the two is that the portable one doesn't auto update, or need installing.

**Comment by Qwerty-Space** [comment]
No I was not.  But I am now since the other one would not install

**Comment by ebkr** [comment]
Ah I see, I just downloaded an older version and gave it a go. That banner wasn't supposed to be there, and upon looking in to it, it turns out I left the correct line commented out, and instead always said it was portable.

Thanks for raising this as an issue. I'll open a new one to fix it.

**Comment by ebkr** [comment]
Raised here: https://github.com/ebkr/r2modmanPlus/issues/150
