### ISSUE TITLE
[BUG] - Sudden Windows 7 incompatibility error

### ISSUE THREAD

**Issue by minyassa** [ebkr/r2modmanPlus#1537]
**Describe the bug**

Error message when I attempt to start R2ModMan: "The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll."

**To Reproduce**
1. Attempt to start R2ModMan

**Expected behavior**

Expect R2ModMan to open like it did until the other day when I updated.

**Additional context**

It's worked just fine until today. Going to attempt to roll back to an earlier release for now.

**Comment by ebkr** [comment]
Unfortunately this is intentional.
Electron was updated to workaround a long term issue on Linux distributions on Wayland. This has meant that Windows 7 support has had to be dropped.

Windows 7 has been end of life for consumers since 2020, and has been end of life for extended support since 10th January 2023. 
See this Microsoft page for evidence: https://learn.microsoft.com/en-us/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq#what-are-the-coverage-dates-for-the-three-windows-7-esu-skus-


We are almost two years past that point and Steam doesn’t even provide updates for Windows 7 anymore.
See this Steam support page for evidence: https://help.steampowered.com/en/faqs/view/4784-4F2B-1321-800A

Overall I don’t see the benefit in having a subpar experience for Linux users at the cost of supporting a no-longer-supported Windows 7.
