### ISSUE TITLE
Can you make booleans in configs be switch buttons or checkboxes instead of textboxes

### ISSUE THREAD

**Issue by Xyvyrianeth** [ebkr/r2modmanPlus#258]

**Comment by ebkr** [comment]
Hi, I've had this mentioned to me a occasionally.

### Answer
The answer is no. Not because I don't want to do it, but because there's some quirks around it.

### Reason
Config files are simply laid out like so:
```
[Section]
key=this is a value
```

Now, there's no way to tell if "value" represents a boolean or a word.

```
[Section]
enabled=true
yesText=true
```

Whilst unlikely that it could happen, I don't want to restrict free-text input because the initial value is "true" rather than "false".

Assuming I implied that any value of "true" or "false" were to be boolean switches/checkboxes, if you were to write "true" or "false" into a field, you'd then be locking it.

To work around this, I could store the state of the initial config. The problem here is (again unlikely) that if a developer changes the type of data stored from boolean to string, EG: to require "yes" or "no", we'd be locked out of the config again. This would require the config to be deleted.

### Summary
No, as it's not worth guessing the value in case of future changes. It could result in a user having a broken config that would need to be deleted.

Feel free to reply to this issue, I'll close it for now though.

**Comment by JohnEdwa** [comment]
The proper way to implement this, and which was done by[ BepinEx ConfigurationManager](https://thunderstore.io/package/IFixYourRoR2Mods/Bepinex_ConfigurationManager/) is requiring mod developers to utilize the BepinEx [AcceptableValueList](https://bepinex.github.io/bepinex_docs/master/api/BepInEx.Configuration.AcceptableValueList-1.html) and Range.

It makes this ``DisableSpeedlines = Config.Bind<bool>("", "DisableSpeedlines", false, new ConfigDescription("Disables speedlines while sprinting", new AcceptableValueList<bool>(true, false)));`` produce a config section like this:

```
## Disables the (useless) sprinting crosshair.
# Setting type: Boolean
# Default value: true
# Acceptable values: True, False
DisableSprintingCrosshair = true
```

And this ``CustomFOV = Config.Bind<int>("Visual", "FOVValue", -1, new ConfigDescription("Change FOV. Default is 60, set to -1 to disable.", new AcceptableValueRange<int>(-1, 359)));``

produces this
```
## Change FOV. Default is 60, set to -1 to disable.
# Setting type: Int32
# Default value: -1
# Acceptable value range: From -1 to 359
FOVValue = -1
```

r2modman could therefore parse the `Setting type` and  `Acceptable value range` sections from the config and use those to implement the proper controls.
