### ISSUE TITLE
[BUG] - Auto-Update on close/relaunch uninstalls the program entirely and does not install a new version

### ISSUE THREAD

**Issue by inverlock** [ebkr/r2modmanPlus#269]
Windows 10 home 2004
19041.450

When the pop-up appears telling me that a new update has been downloaded relaunch to apply, I do so and it requests permission for an "uninstaller-old", which then uninstalls the program and i have to go download the new version manually.

**Comment by ebkr** [comment]
This is known, and also something that relates to permissions on your machine.
You should be able to get around this by installing the manager without admin permissions.

**Comment by paweston70** [comment]
> You should be able to get around this by installing the manager without admin permissions.

That's not a solution, it's a workaround at best.

**Comment by RatserX** [comment]
> You should be able to get around this by installing the manager without admin permissions.

What's the point of the option to install for all users then? If it's going to need admin permissions and then fail afterwards when updating, why is it even there?

**Comment by ebkr** [comment]
That’s just a consequence of letting you choose where to install the manager to.

This isn’t something I have control over as the updater is NSIS which isn’t something I’ve created and is done as part of the build process. It’s not trivial to change to change to a different auto-updater.

I can remove the option to change the install location entirely which prevents these things from happening, but I’d rather not because it’s nice to be able to install it on a separate drive.

> That's not a solution, it's a workaround at best.

Yeah, it’s a workaround, hence the “You should be able to get around this”. I’m aware it’s a less than ideal response but as far as I can see from documentation, it’s out of my hands
