### ISSUE TITLE
[FEATURE REQUEST] - Releases + packages + tutorial for installing on Linux

### ISSUE THREAD

**Issue by StarrKiss** [ebkr/r2modmanPlus#382]
Now that we've got Linux support, R2Modman should be added to the AUR, builds should be released as .deb or .appimage to use, and README should include a tutorial for installation.

**Comment by ebkr** [comment]
Linux is not officially supported yet.
The PR has been merged, but there are no current releases.

AUR is not planned, but AppImage and tar packages are.

**Comment by AryToNeX** [comment]
@StarrKiss

First off, there's no need for an installation tutorial, because literally everyone knows how to double click a .deb or .appimage file (that, if you look at the source code, will be built and released on GitHub in the Releases section).

Lastly, if you didn't know, AUR stands for Arch User Repository, and everyone can contribute to it. Therefore, this feature request is pointless (it may AT BEST be a suggestion, not a request, because - again - you can make the PKGBUILD yourself)

As for releases, they will arrive once r2modman 3.1 (ebkr correct me if I am wrong) arrives for everyone, and they will feature packages for all the major distros (including Arch, if that's your question).

---

If you cannot wait, you can just build the package off the master branch yourself.
```sh
git clone https://github.com/ebkr/r2modmanPlus
cd r2modmanPlus
yarn && yarn build-linux
sudo pacman -U dist/electron/Packaged/r2modman-plus*.pacman
```

**Comment by ebkr** [comment]
Just updated it to reflect more recent building instructions, but this should be sufficient for requirements.

**Comment by Paulemeister** [comment]
Maybe i just don't know how to properly run the AppImage, but it seems like i have to manually create the simlink from r2modman/BepInEx to ~.config/r2modmanPlus-local/mods/profiles/Standard/BepInEx. This will not be updated when switching profiles in the modmanager. (paths are set correctly).

I used the AppImage that was uploaded, cause I couldn't figure out how to compile it properly for debian(or in general).

Also I never added parameters for WINE inside the steam launch options before, so it took a while to figure out that I had to put `WINEDLLOVERRIDES="winhttp=n,b %command%` at the beginning.


I tested importing profiles, and it works just fine

I'm running Pop!_OS 20.10 and my kernel is  5.8.0-7630-generic.

**Comment by AryToNeX** [comment]
> Maybe i just don't know how to properly run the AppImage, but it seems like i have to manually create the simlink from r2modman/BepInEx to ~.config/r2modmanPlus-local/mods/profiles/Standard/BepInEx. This will not be updated when switching profiles in the modmanager. (paths are set correctly).
> 
> I used the AppImage that was uploaded, cause I couldn't figure out how to compile it properly for debian(or in general).
> 
> Also I never added parameters for WINE inside the steam launch options before, so it took a while to figure out that I had to put `WINEDLLOVERRIDES="winhttp=n,b %command%` at the beginning.
> 
> I tested importing profiles, and it works just fine
> 
> I'm running Pop!_OS 20.10 and my kernel is 5.8.0-7630-generic.

I get you're coming from the Steam guide on RoR2 Linux modding.
That AppImage was made a month ago and it lacks all the polish that the `master` branch now has. It also is based off an old source code. That's why you get all those issues.
Please consider running r2modman from source if you're still experiencing issues.

**Comment by Paulemeister** [comment]
yep resolved the issue

**Comment by ebkr** [comment]
A little late but the latest release has AppImage, Deb, RPM, and Pacman builds
