### ISSUE TITLE
[Feature Request] Terminate on game terminate

### ISSUE THREAD

**Issue by kris44dad** [ebkr/r2modmanPlus#447]
**What problem does the feature request solve?**
Eliminates the need to terminate your program when you exit the game

**Example mock-up (optional)**
Add a checkbox option for each game on the game selection screen to terminate your mod tool upon termination of the game itself to automate the game shutdown process.

**Additional information (optional)**
_Enter additional information here_

**Comment by ebkr** [comment]
Thanks for raising the issue.

> to automate the game shutdown process.

I don't feel as though the game and the manager are directly related. The game is launched via Steam rather than the manager itself, and so the process isn't visible unless actively scanning running processes, making this slightly awkard to do.

There are also plenty of scenarios where someone could tick this option, install a bad mod, crash their game, and then in turn cause the manager to quit. It's not ideal and seems more inconvenient if anything.

This feels like a wontfix issue, however I'll leave the issue open if there's another reason.

In a similar manner, other mod managers that I've used don't close themselves when the game closes.

**Comment by kris44dad** [comment]
Thanks for the reply. Not a big issue. I could script this myself but before I do I would need to know, how would your manager handle a termination via a task kill?
    On Monday, March 22, 2021, 07:26:35 AM CDT, Cade Ayres ***@***.***> wrote:  
 
 


Thanks for raising the issue.


to automate the game shutdown process.


I don't feel as though the game and the manager are directly related. The game is launched via Steam rather than the manager itself, and so the process isn't visible unless actively scanning running processes, making this slightly awkard to do.

There are also plenty of scenarios where someone could tick this option, install a bad mod, crash their game, and then in turn cause the manager to quit. It's not ideal and seems more inconvenient if anything.

This feels like a wontfix issue, however I'll leave the issue open if there's another reason.

In a similar manner, other mod managers that I've used don't close themselves when the game closes.

**Comment by ebkr** [comment]
Should handle it correctly afaik, Electron should handle that.
