### ISSUE TITLE
[BUG/INFO] - Update installed without asking and to different location.

### ISSUE THREAD

**Issue by Shad0wlife** [ebkr/r2modmanPlus#474]
**Describe the bug**
The 3.1.10 update was installed without asking for an installation and to an entirely different folder (even a different drive) than it was installed before. Earlier today I was still using 3.1.9, after a reboot a second desktop icon for r2modman appeared, pointing to an entirely different path (in localappdata now, while the old icon still points to my program files folder on F:).

**To Reproduce**
(I don't know if external factors played into it - and I have not tried reproducing it yet)
1. Install 3.1.9 on a different drive in some custom folder
2. Let it autoupdate
3. 3.1.10 is installed in %localappdata%/Programs

**Expected behavior**
If the program does not know where to install its update or requires elevated privileges to install into its current location, it should request the install path or privileges instead of silently installing somehwere else.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/15235997/114074703-f5278b00-98a4-11eb-9fa9-3b314a81d834.png)
(Left is 3.1.10, in AppData/Local, rigtht is the original install, which is still 3.1.9 and does not actually launch properly anymore)

**Additional context**
 \- None -

**Comment by ebkr** [comment]
Hi, I've picked this up in the DSP modding discord but I'll mention it here again:

NSIS is the installer and I don't maintain anything regarding it.
Electron-builder bundles the app into an installable EXE using NSIS.

Not sure why it isn't overwriting the previous version, although is likely due to registry keys.

This issue has happened once before however resolved itself in a subsequent release, so it might just be a partially failed build? Either way, there's not really too much I can do about it on my end.
