### ISSUE TITLE
[FEATURE REQUEST] - Allow importing multiple local packages simultaneously

### ISSUE THREAD

**Issue by notpeelz** [ebkr/r2modmanPlus#569]

**Comment by ebkr** [comment]
So I've been looking in to this a little more and it's quite a pain.

With the whole modal popup now rather than instant importing, it's a little harder to make it clean without spamming people with constant popups. I mean, that's one solution, but I can imagine a lot of people would get annoyed with several modal switches.

I might delay it for a while to see if I can come up with anything better.
