### ISSUE TITLE
[FEATURE REQUEST] - Export mod list separately from configs

### ISSUE THREAD

**Issue by Fidgetcetera** [ebkr/r2modmanPlus#596]
**What problem does the feature request solve?**
When playing in a group setting, our group members cannot individually have unlocks because the unlocks get overriden by importing a profile.

**Additional information (optional)**
Would just love to have "export configs" be a checkbox near the "export profile" button, and the same checkbox for importing a profile.

**Comment by ebkr** [comment]
I don't think there's much use for this since the majority of the time you'd need matching config files.

The point in exporting your profile is to produce an exact copy (as much as possible) as someone else's.
This has the potential to mislead users and frequently cause problems where the config files haven't been copied across.

You can manually modify it by exporting as a file, renaming the profile export extension from `.r2z` to `.zip` and removing the `config` folder inside.

**Comment by Fidgetcetera** [comment]
Right. I think our group mistakenly thought that save data for unlocks was stored in a mod's config (and thus was getting reset) in a case where it wasn't, so I think I agree here. Sorry!
