### ISSUE TITLE
[BUG] - Empty R2Modman folder

### ISSUE THREAD

**Issue by AefRal** [ebkr/r2modmanPlus#829]
**Describe the bug**
Noticed a blank icon on my taskbar, hovered to identify, it's R2Modman. 
Right-click->properties->Open File Location.
Find an empty folder...
Where'd it go?

I have no idea what happened, but R2Modman is the only program that 
it happened to.
I'm downloading the latest (3.1.31) now.
The previous version I had in my downloads folder was 3.1.29.
Maybe this was caused when it tried to auto-install the update?
Are the mods stored in a different directory?
Hope I didn't lose everything.

**Comment by AefRal** [comment]
I clicked run, when it finished installing 3.1.31, an it asked me to help it locate it. So I go to the install location and it's empty.
What did I just install?

**Comment by ebkr** [comment]
Sorry for the extremely late response. I haven't been on top of the issues for a while.

This happened because you installed the manager somewhere other than the default location, which sometimes has the effect of causing the auto updater to fail. When it fails it wipes the folder entirely.

The solution is to reinstall the latest version.

**Comment by AefRal** [comment]
Reinstalling the latest version has the same effect. About a week later I
thought to try running the installation as administrator, which worked.
