### ISSUE TITLE
Allow two instances of the program running at the same time

### ISSUE THREAD

**Issue by bnn1** [ebkr/r2modmanPlus#839]
It's impossible to launch two instances of r2modman on Windows 11.

But when modding the game it's sometimes needed, for example to see what mods are present in one profile.

**Comment by ebkr** [comment]
It's intentional because of the "install with mod manager" button. The OS tries to launch another instance of the manager, and that'd be weird.

It's a very niche issue. Why exactly do you need to see what's on another profile?
If it's to duplicate one, just export and re-import the profile with a new name.

**Comment by bnn1** [comment]
Say I'm creating a profile and I want to pick some mods from other profile. I can't remember all the mods I want to install so I got to switch back and forth from profile to profile.

**Comment by ebkr** [comment]
Late reply but this definitely seems like something you'd just export and re-import a profile for.
Alternatively you can also go to `Settings -> Show dependency strings` and just copy/paste the contents into notepad
