### ISSUE TITLE
[BUG] - Risk of Rain 2 not opening modded on Linux

### ISSUE THREAD

**Issue by al12gamer** [ebkr/r2modmanPlus#904]
**Describe the bug**
Risk of Rain 2, on my Fedora-based Nobara Linux install, will not open modded when launching from the most recent r2modman 3.1.34 appimage nor rpm install.

**To Reproduce**
(see video)

**Expected behavior**
Risk of Rain 2 should be starting modded.

**Screenshots**
(see video)

https://user-images.githubusercontent.com/10056498/206022919-ae690d47-b5e8-41bd-b8b4-448669d84290.mp4

**Comment by ebkr** [comment]
The issue you commented on isn't quite the same as this.

Have you tried making a new profile with only BepInEx installed?

**Comment by al12gamer** [comment]
I will give that a shot soon and comment to see if it helps

**Comment by al12gamer** [comment]
Didn't end up working. I'm driving for a few days soon, so I'll try messing with modman again when I get to where I'm going. Oddly enough, this used to work with those mods and by hitting Launch Modded without any odd steps or launch commands back in October. Wonder what changed in the Fedora land...

**Comment by 7RW** [comment]
Facing the same problem on Pop!_OS 22.04. Got as far as figuring out that RoR2 won't launch as soon as I have the "%command%" part in the steam launch options. 
Without that it launches (without mods obviously), with it the game won't launch no matter what mods are installed. I tested with a couple of mods (BetterUI, ItemStats, and dependencies), only BepInEx and vanilla, none of them worked.

Side note that might not have anything to do with the issue here: As I was facing the issues mentioned in #735  earlier I am launching r2modman with the "--no-sandbox" flag.

**Comment by al12gamer** [comment]
It seems we might have a workaround temporarily from this issue?
https://github.com/ebkr/r2modmanPlus/issues/927#issuecomment-1364939059

**Comment by al12gamer** [comment]
As I've gone ahead and installed the required bits via the CLI tool mentioned in https://github.com/ebkr/r2modmanPlus/issues/927#issuecomment-1364939059 I can go ahead and run any mods I have via the r2modman tool, so I'm going to close this for now
