### ISSUE TITLE
[FEATURE REQUEST] - Make the search more responsive

### ISSUE THREAD

**Issue by xiaoxiao921** [ebkr/r2modmanPlus#905]
There are so many packages the app freeze / unresponsive when you search a mod through its name

**Comment by MythicManiac** [comment]
@xiaoxiao921 is this with the latest version? I'm pretty sure @ebkr did some optimizations for it recently and it seemed to run well. Not sure if those were released yet however.

As for the issue, I'd reframe it to "make the search more responsive" since I doubt multithreading is required for it. Just adding a debounce should help quite a bit

**Comment by xiaoxiao921** [comment]
Yes, this was done using r2modman 3.1.34
There is a noticeable delay until keystroke are "acknowledged" through the UI, the search bar doesnt actually update its text until i'd say a good second, sometimes 2 on my machine.
a good repro case is to select risk of rain 2, go in the "Online" tab, and quickly write "Artifact" in the search bar, the whole UI will freeze

**Comment by ebkr** [comment]
I think this was resolved a while back, can you confirm?

**Comment by xiaoxiao921** [comment]
Yeah it's better now, just tried again just to be safe
