### ISSUE TITLE
[BUG] - Installing a modpack does not install the versions from the manifest but latest versions

### ISSUE THREAD

**Issue by himpich** [ebkr/r2modmanPlus#929]
**Describe the bug**
I have a modpack with given modnames and versions. If I install it, r2modman does not install the given versions but installes the latest version of the mods. This breaks compatibility of the modpack versions and makes the versions in the manifest obsolete

**To Reproduce**
1. Install v2.0.7 of https://valheim.thunderstore.io/package/SmartS/Godmins_Modpack_season_2/
2. The manifest states to install JereKuusela-Item_Stand_All_Items-1.14.0
3. JereKuusela-Item_Stand_All_Items-1.15.0 gets installed, as it is the latest version

**Expected behavior**
r2modman installs the versions of the mods specified in the manifest file

**Comment by MythicManiac** [comment]
It's a bit of a hidden feature, but you need to categorize your upload as a modpack for the versions to be strictly respected. While it is documented (https://github.com/ebkr/r2modmanPlus/wiki/Modpacks), it isn't very intuitive behavior and is likely going to be changed to be more explicitly controllable e.g. in the manifest.

So due to the above, I'll close this task, but feel free to re-open if you disagree or have issues with the solution

**Comment by himpich** [comment]
works for me. I guess a hint in the upload menu would be nice (to explain what "modpack" means). I did not choose modpack for my modpack as it wasn't listed in a feed of new mods on the "Valheim Modding" Discord. But now I know and will choose "modpack" in the future. Thanks
