### ISSUE TITLE
Change the license

### ISSUE THREAD

**Issue by CJendantix** [ebkr/r2modmanPlus#947]
Just a suggestion, but you should really change the license to AGPL, the Azure GNU General Public License, to y'know, stop people from selling your software, also the *Azure* part of the GPL license is not required, but it states that if you modify the code and wish to release it to the public, it needs to be open source.

**Comment by MythicManiac** [comment]
While it's more up to @ebkr to decide what license he'd prefer to use, I figure it's worth noting that changing the license of an open source project isn't the easiest thing to do, as you need to get approval of all of the contributors whose code is still included in the repository or alternatively refactor their code out of it.

That said, I don't think it's a bad idea to consider what the current license actually entails if that hasn't been done yet. I'd assume it has been considered however, and not just arbitrarily picked.

**Comment by ebkr** [comment]
Yeah so MIT was chosen because I quite literally am not bothered with what people choose to do with the manager.

If someone can fork it, make something better, but wish to keep it closed, well that’s generally better for everyone as it’ll result in a better tool. The closed source features can always be implemented in a separate open-source fork.

I don’t want to restrict what people do, nor impose any licence on their work, and MIT is one of the friendliest to incorporate into other projects

**Comment by MythicManiac** [comment]
Based on the comment above, I'm assuming this can be closed. Re-open if necessary.
